# GoAccess
location /monitor {
    alias /var/www/goaccess-monitor;
    index index.php;

    location ~* \.php$ {
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        include fastcgi_params;
    }

    auth_basic "Protected";
    auth_basic_user_file /etc/nginx/.htpasswd;
    proxy_set_header Authorization "";
}